apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: orchestrator
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "0.5"
            requests:
              cpu: "0.25"
