apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 31110
  type: LoadBalancer
