apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  selector:
    app: users
  ports:
    - port: 3001
      protocol: TCP
      nodePort: 30001
  type: LoadBalancer
